// Centralized error codes (see Section 23 of architecture doc)
module.exports = {
  SERVICE_DISABLED: 'SERVICE_DISABLED',
  INVALID_SERVICE_TYPE: 'INVALID_SERVICE_TYPE',
  STOP_SEQUENCE_INVALID: 'STOP_SEQUENCE_INVALID',
  POD_REQUIRED: 'POD_REQUIRED',
  ASSIGNMENT_CONFLICT: 'ASSIGNMENT_CONFLICT',
  ZONE_NOT_FOUND: 'ZONE_NOT_FOUND',
  MERCHANT_CLOSED: 'MERCHANT_CLOSED',
  MENU_ITEM_UNAVAILABLE: 'MENU_ITEM_UNAVAILABLE',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  IDEMPOTENCY_REPLAY: 'IDEMPOTENCY_REPLAY',
  RATE_LIMITED: 'RATE_LIMITED',
  SURGE_UNAVAILABLE: 'SURGE_UNAVAILABLE',
  OPTIMIZER_FAILED: 'OPTIMIZER_FAILED',
  FEATURE_FLAG_OFF: 'FEATURE_FLAG_OFF',
};
